import { type Product, type Category, type User } from './types';

export const CATEGORIES: Category[] = [
  { id: 1, name: 'بهارات' },
  { id: 2, name: 'حبوب' },
  { id: 3, name: 'بقوليات' },
];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'فلفل أسود',
    price: 15.50,
    image: 'https://picsum.photos/seed/pepper/400/300',
    categoryId: 1,
    description: 'فلفل أسود حب كامل عالي الجودة، يضيف نكهة حارة وعطرية لأطباقك.',
    stock: 50,
    status: 'active',
  },
  {
    id: 2,
    name: 'كمون',
    price: 12.00,
    image: 'https://picsum.photos/seed/cumin/400/300',
    categoryId: 1,
    description: 'كمون مطحون طازج، أساسي في المطبخ الشرقي لإعطاء عمق ونكهة مميزة.',
    stock: 100,
    status: 'active',
  },
  {
    id: 3,
    name: 'كركم',
    price: 10.75,
    image: 'https://picsum.photos/seed/turmeric/400/300',
    categoryId: 1,
    description: 'مسحوق الكركم الذهبي، معروف بفوائده الصحية ولونه الزاهي.',
    stock: 0,
    status: 'active',
  },
  {
    id: 4,
    name: 'أرز بسمتي',
    price: 25.00,
    image: 'https://picsum.photos/seed/rice/400/300',
    categoryId: 2,
    description: 'أرز بسمتي هندي حبة طويلة، مثالي للكبسة والبرياني.',
    stock: 200,
    status: 'active',
  },
  {
    id: 5,
    name: 'عدس أحمر',
    price: 8.50,
    image: 'https://picsum.photos/seed/lentils/400/300',
    categoryId: 3,
    description: 'عدس أحمر مجروش، سريع الطهي ومثالي لشوربة العدس الشهية.',
    stock: 150,
    status: 'active',
  },
  {
    id: 6,
    name: 'فول مجروش',
    price: 7.00,
    image: 'https://picsum.photos/seed/fava/400/300',
    categoryId: 3,
    description: 'فول مجروش للطبخ، أساس الفطور الشعبي في العديد من البلدان.',
    stock: 80,
    status: 'inactive',
  },
  {
    id: 7,
    name: 'لوبيا',
    price: 9.25,
    image: 'https://picsum.photos/seed/beans/400/300',
    categoryId: 3,
    description: 'لوبيا بيضاء ذات عين سوداء، غنية بالبروتين والألياف.',
    stock: 120,
    status: 'active',
  },
  {
    id: 8,
    name: 'برغل خشن',
    price: 11.00,
    image: 'https://picsum.photos/seed/bulgur/400/300',
    categoryId: 2,
    description: 'برغل قمح خشن، يستخدم في السلطات مثل التبولة والمجدرة.',
    stock: 75,
    status: 'active',
  },
  {
    id: 9,
    name: 'قرفة عيدان',
    price: 18.00,
    image: 'https://picsum.photos/seed/cinnamon/400/300',
    categoryId: 1,
    description: 'عيدان قرفة سيلانية أصلية، تضفي رائحة ونكهة دافئة للحلويات والمشروبات.',
    stock: 40,
    status: 'active',
  },
  {
    id: 10,
    name: 'حمص',
    price: 10.00,
    image: 'https://picsum.photos/seed/chickpeas/400/300',
    categoryId: 3,
    description: 'حبوب الحمص الكاملة، مثالية لتحضير الحمص بالطحينة والفتة.',
    stock: 30,
    status: 'active',
  },
  {
    id: 11,
    name: 'فريكة',
    price: 14.50,
    image: 'https://picsum.photos/seed/freekeh/400/300',
    categoryId: 2,
    description: 'فريكة خضراء مدخنة، ذات نكهة فريدة ومغذية.',
    stock: 60,
    status: 'active',
  },
  {
    id: 12,
    name: 'هيل',
    price: 35.00,
    image: 'https://picsum.photos/seed/cardamom/400/300',
    categoryId: 1,
    description: 'حبوب هيل أخضر كاملة، لإضافة نكهة فاخرة للقهوة العربية والأطباق.',
    stock: 25,
    status: 'active',
  },
];

export const USERS: User[] = [
    { id: 1, name: 'أحمد المحمد', email: 'ahmad@example.com', role: 'admin' },
    { id: 2, name: 'فاطمة الزهراء', email: 'fatima@example.com', role: 'editor' },
];
